version: '3'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-ce
    hostname: gitlab-ce
    ports:
      - '2224:22'
      - '8024:80'
      - '44324:443'
    volumes:
      - '/srv/docker/pipeline/gitlab/etc:/etc/gitlab'
      - '/srv/docker/pipeline/gitlab/logs:/var/log/gitlab'
      - '/srv/docker/pipeline/gitlab/data:/var/opt/gitlab'
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    hostname: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - '/srv/docker/pipeline/jenkins/data:/var/jenkins_home'
    
